name: chess_game
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_bloc: ^9.1.1
  go_router: ^15.1.2
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  equatable: ^2.0.7
  intl: ^0.20.2
  uuid: ^4.5.1
  injectable: ^2.5.0
  flutter_gen_runner: ^5.10.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0

flutter_gen:
  output: lib/presentation/assets

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
